### ISSUE TITLE
Docker Desktop not working

### ISSUE THREAD

**Issue by pbk20191** [Nevuly/WSL2-Rolling-Kernel-Issue#21]
### Windows Version

Windows 11

### Kernel Release Channel

Stable Release

### Kernel Version

6.10.4

### Distro Version

Ubuntu 22.04

### Other Software

Docker-Desktop (4.33.1)

### Repro Steps

After updating the Docker Desktop to 4.33.1. Docker Desktop is not working. ( Docker Desktop was working normally before update)

### Expected Behavior

Docker Desktop should keep working. Like normal MS wsl2 kernel does.

### Actual Behavior

Using Docker Desktop with 6.10.4 kernel shows me "Shutting down Docker Engine" over and over.

**Comment by Nevuly** [comment]
@pbk20191 

Thanks for leaving issue.

I'll check it in my environment with 6.10.4 kernel.

(I don't have enough time, So It will take time to fix this problem. I'll check it ASAP.)

Thanks.

**Comment by pbk20191** [comment]
I realized that official pre-release kernel has been downgraded back from "6.6" to "5.15".
And Official WSL2 pre-release kernel has same issue. ( I checked it by building the kernel from source)

**Comment by Nevuly** [comment]
> I realized that official pre-release kernel has been downgraded back from "6.6" to "5.15". And Official WSL2 pre-release kernel has same issue. ( I checked it by building the kernel from source)

Okay, Thanks for give information.
관련 정보 주셔서 감사합니다.

I merged some 6.6 kernel features, I must recheck about that.
이전에 6.6 커널의 defconfig 중 일부 내용을 머지한 적이 있는데, 그 기능들을 다시 확인해봐야겠습니다.

Thanks.
감사합니다.

**Comment by Nevuly** [comment]
@pbk20191 

Hello. Today, I completed to check about this issue.
안녕하세요. 오늘 이 문제에 대해 확인을 완료하여 공유 드립니다.

After update to docker desktop version `4.43.1`, It always try to checking wsl2 update.
docker desktop `4.43.1` 버전 업데이트 이후, docker desktop이 프로그램을 시작할 때 마다 wsl2 업데이트를 확인합니다.

You can check about that issue in below:
해당 이슈는 docker 공식 깃허브에도 공유되었으니, 아래 내용을 확인해보세요:
https://github.com/docker/for-win/issues/14240

I checked that issue thread, docker developer shared test version about disable it:
공유드린 이슈 스레드를 확인해 보니, 개발자분이 wsl2 업데이트를 비활성화 한 테스트 버전을 공유해주셨습니다:
https://github.com/docker/for-win/issues/13868#issuecomment-2271513666

I installed that version, and check docker desktop again, and I confirmed It keep try to access `lib/modules` directory.
제 시스템에 해당 버전을 설치하고 확인하니, docker desktop에서 시작할 때마다 `lib/modules` 디렉토리에 접근을 시도하는 것이 확인되었고, 디렉토리가 없어 오류가 발생하는 것을 확인했습니다.

In `4.43.1` changelog in below:
docker desktop `4.43.1`의 변경사항은 다음과 같습니다:
`Added support for WSL2 2.3.11 and above, which includes loadable kernel modules.`
`WSL2 2.3.11 또는 그 이후 버전에서 로드 가능한 커널 모듈을 지원합니다.`

WSL2 custom kernels can't install kernel modules automatically, So you need to install it in `docker-desktop` WSL2 image manually.
아시다 싶이, WSL2 커스텀 커널은 커널 모듈을 모든 이미지에 자동으로 설치할 수 없기 때문에, `docker-desktop` WSL2 이미지에 수동으로 접근하여 커널 모듈을 설치하셔야 합니다.

After install kernel modules in `docker-desktop` WSL2 image, I confirmed It works correctly again.
설치 이후 제 시스템에서 docker-desktop이 다시 정상동작 하는 것을 확인하였습니다.

![image](https://github.com/user-attachments/assets/22363de2-9c99-484e-899e-d9cd74dfe403)

If you need a guide about install kernel modules in `docker-desktop` WSL2 image, please leave comment.
만약, `docker-desktop` WSL2 이미지에 커널 모듈 설치 가이드가 필요하시다면, 답변을 달아주시면 감사하겠습니다.

Thanks.
감사합니다.

**Comment by pbk20191** [comment]
Thanks for your detail explanation.
I appreciate your help

**Comment by Nevuly** [comment]
> Thanks for your detail explanation. I appreciate your help. Can I have detail guideline of installing kernel-module?

1. Please type command in below: (type in CMD)
`wsl -d docker-desktop`

After type that, you can access `docker-desktop` WSL2 image.

2. Download kernel-modules tarball zip and paste it in docker-desktop WSL2 directory. You can access it in explorer

3. unzip kernel-modules tarball in WSL2 terminal.

4. paste x.x.x-WSL2-xxxx+ directory in `lib/modules`. If `lib/modules` not exists, please create it.

5. Shutdown your WSL2 and turn off the docker desktop. and restart it.

After doing that procedure, you can use docker-desktop again.

Thanks.

**Comment by huangxiaofeng10047** [comment]
@Nevuly after install the ·6.10.4-wsl-STABLE+· into the  /lib/modules ,I success.
![image](https://github.com/user-attachments/assets/80b27885-c269-46a7-8107-7edd762c245e)
![image](https://github.com/user-attachments/assets/4158ff3d-f993-4d27-b360-77211434adb2)

**Comment by Nevuly** [comment]
> @Nevuly after install the ·6.10.4-wsl-STABLE+· into the /lib/modules ,I success. ![image](https://private-user-images.githubusercontent.com/16282496/360357407-80b27885-c269-46a7-8107-7edd762c245e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzOTk2MjcsIm5iZiI6MTcyNDM5OTMyNywicGF0aCI6Ii8xNjI4MjQ5Ni8zNjAzNTc0MDctODBiMjc4ODUtYzI2OS00NmE3LTgxMDctN2VkZDc2MmMyNDVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDA3NDg0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmYjY3MjRhOTVhMDUwNmI4OWJkOWFlOWI4YzlkOGQ3OTAzNTE0MTE2ZWFjNjUwODYwYzg2NDQ0Njg5YmM4YTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w5KsHvONTBrRPTEbIMAE-oWdxx4NQfRODfwNtn0KJYE) ![image](https://private-user-images.githubusercontent.com/16282496/360357491-4158ff3d-f993-4d27-b360-77211434adb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzOTk2MjcsIm5iZiI6MTcyNDM5OTMyNywicGF0aCI6Ii8xNjI4MjQ5Ni8zNjAzNTc0OTEtNDE1OGZmM2QtZjk5My00ZDI3LWIzNjAtNzcyMTE0MzRhZGIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDA3NDg0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3NmIyY2NiMDc1NDA0YzJkNTJhZjdmYTI3MDQxNzZlZmI1ZjM3ZTljZTg2NjU0YWFkZTFiYmJmM2YyNzViN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iXf25bEnTqnTqjjIim6kakhe-hp4xZbH-ctBipe8WJU)

Great.

Thanks for testing about that. :)

**Comment by Nevuly** [comment]
After docker desktop v4.37.1, It works correctly without install kernel modules.
